export const SECTOR_ETF_BY_NAME: Record<string, string> = {
  Technology: "XLK",
  "טכנולוגיה": "XLK",
  Healthcare: "XLV",
  "בריאות": "XLV",
  "Financial Services": "XLF",
  "שירותים פיננסיים": "XLF",
  Energy: "XLE",
  "אנרגיה": "XLE",
  "Consumer Cyclical": "XLY",
  "צריכה מחזורית": "XLY",
  "Consumer Defensive": "XLP",
  "צריכה בסיסית": "XLP",
  Industrials: "XLI",
  "תעשייה": "XLI",
  "Communication Services": "XLC",
  "תקשורת": "XLC",
  "Real Estate": "XLRE",
  "נדל\"ן": "XLRE",
  "Basic Materials": "XLB",
  "חומרי גלם": "XLB",
  Utilities: "XLU",
  "תשתיות": "XLU",
};